/**
 * Updated on 2022-03-03
 */
module.exports = [
  { code: "a78", value: "AHUNTSIC" },
  { code: "m18", value: "BELLEVILLE" },
  { code: "c56", value: "BENNY" },
  { code: "c58", value: "BIBLIOTHEQUE INTERCULTURELLE" },
  { code: "s85", value: "DU BOISE" },
  { code: "a79", value: "CARTIERVILLE" },
  { code: "c57", value: "COTE-DES-NEIGES" },
  { code: "f53", value: "FRONTENAC" },
  { code: "j15", value: "HAUT-ANJOU" },
  { code: "m17", value: "HENRI-BOURASSA" },
  { code: "h26", value: "HOCHELAGA" },
  { code: "v76", value: "ÎLE DES SOEURS" },
  { code: "v75", value: "J-DE REPENTIGNY (Verdun)" },
  { code: "j14", value: "JEAN-CORBEIL" },
  { code: "r39", value: "LA PETITE-PATRIE" },
  { code: "h27", value: "LANGELIER" },
  { code: "x33", value: "LE PREVOST" },
  { code: "i90", value: "L'ÎLE-BIZARD" },
  { code: "l71", value: "L'OCTOGONE" },
  { code: "m20", value: "BIBLIOTHEQUE DE LA MCC" },
  { code: "h29", value: "MAISONNEUVE" },
  { code: "r41", value: "MARC-FAVREAU" },
  { code: "g64", value: "MARIE-UGUAY" },
  { code: "h28", value: "MERCIER" },
  { code: "y47", value: "MORDECAI-RICHLER" },
  { code: "c59", value: "N-D-DE-GRACE)" },
  { code: "o45", value: "OUTREMONT (Robert-Bourassa)" },
  { code: "x34", value: "PARC-EXTENSION " },
  { code: "f52", value: "PERE-AMBROISE" },
  { code: "p87", value: "PIERREFONDS" },
  { code: "y48", value: "PLATEAU MONT-ROYAL" },
  { code: "t10", value: "POINTE-AUX-TREMBLES" },
  { code: "g63", value: "RÉJEAN-DUCHARME" },
  { code: "t11", value: "RIVIERE-DES-PRAIRIES" },
  { code: "r40", value: "ROSEMONT" },
  { code: "g66", value: "SAINT-CHARLES" },
  { code: "g65", value: "SAINT-HENRI" },
  { code: "n22", value: "SAINT-LEONARD" },
  { code: "x35", value: "SAINT-MICHEL" },
  { code: "b69", value: "SAINT-PIERRE" },
  { code: "a80", value: "SALABERRY" },
  { code: "b68", value: "SAUL-BELLOW" },
  { code: "s84", value: "VIEUX-SAINT-LAURENT" },
  { code: "m19", value: "YVES-RYAN" },
  { code: "zse", value: "BIBLIO-COURRIER" },
  { code: "zcr", value: "COLLECTION RESEAU" },
  { code: "zbmp", value: "SERVICE DE PEB" },
  { code: "zddb", value: "Z-DIR DES BIBLIOTHEQUES (Admin)" },
  { code: "p88", value: "WILLIAM-G.-BOLL (DO NOT CHOOSE)" },
];
